export declare const StyleProps: string[];
export declare const ColorPallete: {
    red: string;
    coral: string;
    orange: string;
    gold: string;
    yellow: string;
    lime: string;
    lightGreen: string;
    green: string;
    darkGreen: string;
    nature: string;
    teal: string;
    aqua: string;
    sky: string;
    lightBlue: string;
    blue: string;
    darkBlue: string;
    blueViolet: string;
    violet: string;
    indigo: string;
    purple: string;
    magenta: string;
    pink: string;
    hotPink: string;
    black: string;
    gray: string;
    white: string;
};
export type ReducedRangeSizes = Omit<Omit<typeof DefaultSizes, "2k">, "4k">;
export declare const DefaultSizes: {
    us: number;
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    "2k": number;
    "4k": number;
};
export declare const DefaultBreakpoints: {
    us: number;
    xs: number;
    sm: number;
    md: number;
    lg: number;
    xl: number;
    "2k": number;
    "4k": number;
};
export declare const SizeRegex: RegExp;
export declare const ColorIntensity = "(100|150|200|250|300|350|400|450|500|550|600|650|700|750|800|850|900)";
